#ifndef __CONFIG_H__
#define __CONFIG_H__

#define ARTILLERYOS_MAX_INTERRUPT_SIZE 0x200
#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10
#define ARTILLERY_OS_VERSION "Version: 0.0.1-alpha"

#endif