#ifndef _CONFIG_H
#define _CONFIG_H

#define IRQ_BASE 0x20
#define ARTILLERYOS_MAX_INTERRUPT_SIZE 256
#define ARTILLERYOS_GDT_SIZE 3
#define ARTILLERYOS_PAGE_SIZE 1024
#define POSITIVE_OUTPUT "[+] "
#define NEGATICVE_OUTPUT "[-] "

#endif