#ifndef __VGA_COLOR_H__
#define __VGA_COLOR_H__

enum VGA_COLOR {
	VGA_COLOR_BLACK = 0X00,
	VGA_COLOR_BLUE = 0X01,
	VGA_COLOR_GREEN = 0X02,
	VGA_COLOR_CYAN = 0X03,
	VGA_COLOR_RED = 0X04,
	VGA_COLOR_MAGENTA = 0X05,
	VGA_COLOR_BROWN = 0X06,
	VGA_COLOR_WHITE = 0X07,
	VGA_COLOR_GRAY = 0X08,
	VGA_COLOR_LIGHT_BLUE = 0X09,
	VGA_COLOR_LIGHT_GREEN = 0X0A,
	VGA_COLOR_LIGHT_CYAN = 0X0B,
	VGA_COLOR_LIGHT_RED = 0X0C,
	VGA_COLOR_LIGHT_MAGENTA = 0X0D,
	VGA_COLOR_YELLOW = 0X0E,
	VGA_COLOR_BRIGHT_WHITE = 0X0F

};

#endif