#include "interrupt.h"

idt_entry_t idt[ARTILLERYOS_MAX_INTERRUPT_SIZE];
idt_ptr_t idt_ptr;

// Interruptmanager Interrupt stubs for ASM
extern void im_int_stub_0(void);

/*
extern void im_int_stub_1(void);
extern void im_int_stub_2(void);
extern void im_int_stub_3(void);
extern void im_int_stub_4(void);
extern void im_int_stub_5(void);
extern void im_int_stub_6(void);
extern void im_int_stub_7(void);
extern void im_int_stub_8(void);
extern void im_int_stub_9(void);
extern void im_int_stub_10(void);
extern void im_int_stub_11(void);
extern void im_int_stub_12(void);
extern void im_int_stub_13(void);
extern void im_int_stub_14(void);
extern void im_int_stub_15(void);
extern void im_int_stub_16(void);
extern void im_int_stub_17(void);
extern void im_int_stub_18(void);
extern void im_int_stub_19(void);
extern void im_int_stub_20(void);
extern void im_int_stub_21(void);
extern void im_int_stub_22(void);
extern void im_int_stub_23(void);
extern void im_int_stub_24(void);
extern void im_int_stub_25(void);
extern void im_int_stub_26(void);
extern void im_int_stub_27(void);
extern void im_int_stub_28(void);
extern void im_int_stub_29(void);
extern void im_int_stub_30(void);
extern void im_int_stub_31(void);
extern void im_int_stub_32(void);
extern void im_int_stub_33(void);
extern void im_int_stub_34(void);
extern void im_int_stub_35(void);
extern void im_int_stub_36(void);
extern void im_int_stub_37(void);
extern void im_int_stub_38(void);
extern void im_int_stub_39(void);
extern void im_int_stub_40(void);
extern void im_int_stub_41(void);
extern void im_int_stub_42(void);
extern void im_int_stub_43(void);
extern void im_int_stub_44(void);
extern void im_int_stub_45(void);
extern void im_int_stub_46(void);
extern void im_int_stub_47(void);
extern void im_int_stub_48(void);
extern void im_int_stub_49(void);
extern void im_int_stub_50(void);
extern void im_int_stub_51(void);
extern void im_int_stub_52(void);
extern void im_int_stub_53(void);
extern void im_int_stub_54(void);
extern void im_int_stub_55(void);
extern void im_int_stub_56(void);
extern void im_int_stub_57(void);
extern void im_int_stub_58(void);
extern void im_int_stub_59(void);
extern void im_int_stub_60(void);
extern void im_int_stub_61(void);
extern void im_int_stub_62(void);
extern void im_int_stub_63(void);
extern void im_int_stub_64(void);
extern void im_int_stub_65(void);
extern void im_int_stub_66(void);
extern void im_int_stub_67(void);
extern void im_int_stub_68(void);
extern void im_int_stub_69(void);
extern void im_int_stub_70(void);
extern void im_int_stub_71(void);
extern void im_int_stub_72(void);
extern void im_int_stub_73(void);
extern void im_int_stub_74(void);
extern void im_int_stub_75(void);
extern void im_int_stub_76(void);
extern void im_int_stub_77(void);
extern void im_int_stub_78(void);
extern void im_int_stub_79(void);
extern void im_int_stub_80(void);
extern void im_int_stub_81(void);
extern void im_int_stub_82(void);
extern void im_int_stub_83(void);
extern void im_int_stub_84(void);
extern void im_int_stub_85(void);
extern void im_int_stub_86(void);
extern void im_int_stub_87(void);
extern void im_int_stub_88(void);
extern void im_int_stub_89(void);
extern void im_int_stub_90(void);
extern void im_int_stub_91(void);
extern void im_int_stub_92(void);
extern void im_int_stub_93(void);
extern void im_int_stub_94(void);
extern void im_int_stub_95(void);
extern void im_int_stub_96(void);
extern void im_int_stub_97(void);
extern void im_int_stub_98(void);
extern void im_int_stub_99(void);
extern void im_int_stub_100(void);
extern void im_int_stub_101(void);
extern void im_int_stub_102(void);
extern void im_int_stub_103(void);
extern void im_int_stub_104(void);
extern void im_int_stub_105(void);
extern void im_int_stub_106(void);
extern void im_int_stub_107(void);
extern void im_int_stub_108(void);
extern void im_int_stub_109(void);
extern void im_int_stub_110(void);
extern void im_int_stub_111(void);
extern void im_int_stub_112(void);
extern void im_int_stub_113(void);
extern void im_int_stub_114(void);
extern void im_int_stub_115(void);
extern void im_int_stub_116(void);
extern void im_int_stub_117(void);
extern void im_int_stub_118(void);
extern void im_int_stub_119(void);
extern void im_int_stub_120(void);
extern void im_int_stub_121(void);
extern void im_int_stub_122(void);
extern void im_int_stub_123(void);
extern void im_int_stub_124(void);
extern void im_int_stub_125(void);
extern void im_int_stub_126(void);
extern void im_int_stub_127(void);
extern void im_int_stub_128(void);
extern void im_int_stub_129(void);
extern void im_int_stub_130(void);
extern void im_int_stub_131(void);
extern void im_int_stub_132(void);
extern void im_int_stub_133(void);
extern void im_int_stub_134(void);
extern void im_int_stub_135(void);
extern void im_int_stub_136(void);
extern void im_int_stub_137(void);
extern void im_int_stub_138(void);
extern void im_int_stub_139(void);
extern void im_int_stub_140(void);
extern void im_int_stub_141(void);
extern void im_int_stub_142(void);
extern void im_int_stub_143(void);
extern void im_int_stub_144(void);
extern void im_int_stub_145(void);
extern void im_int_stub_146(void);
extern void im_int_stub_147(void);
extern void im_int_stub_148(void);
extern void im_int_stub_149(void);
extern void im_int_stub_150(void);
extern void im_int_stub_151(void);
extern void im_int_stub_152(void);
extern void im_int_stub_153(void);
extern void im_int_stub_154(void);
extern void im_int_stub_155(void);
extern void im_int_stub_156(void);
extern void im_int_stub_157(void);
extern void im_int_stub_158(void);
extern void im_int_stub_159(void);
extern void im_int_stub_160(void);
extern void im_int_stub_161(void);
extern void im_int_stub_162(void);
extern void im_int_stub_163(void);
extern void im_int_stub_164(void);
extern void im_int_stub_165(void);
extern void im_int_stub_166(void);
extern void im_int_stub_167(void);
extern void im_int_stub_168(void);
extern void im_int_stub_169(void);
extern void im_int_stub_170(void);
extern void im_int_stub_171(void);
extern void im_int_stub_172(void);
extern void im_int_stub_173(void);
extern void im_int_stub_174(void);
extern void im_int_stub_175(void);
extern void im_int_stub_176(void);
extern void im_int_stub_177(void);
extern void im_int_stub_178(void);
extern void im_int_stub_179(void);
extern void im_int_stub_180(void);
extern void im_int_stub_181(void);
extern void im_int_stub_182(void);
extern void im_int_stub_183(void);
extern void im_int_stub_184(void);
extern void im_int_stub_185(void);
extern void im_int_stub_186(void);
extern void im_int_stub_187(void);
extern void im_int_stub_188(void);
extern void im_int_stub_189(void);
extern void im_int_stub_190(void);
extern void im_int_stub_191(void);
extern void im_int_stub_192(void);
extern void im_int_stub_193(void);
extern void im_int_stub_194(void);
extern void im_int_stub_195(void);
extern void im_int_stub_196(void);
extern void im_int_stub_197(void);
extern void im_int_stub_198(void);
extern void im_int_stub_199(void);
extern void im_int_stub_200(void);
extern void im_int_stub_201(void);
extern void im_int_stub_202(void);
extern void im_int_stub_203(void);
extern void im_int_stub_204(void);
extern void im_int_stub_205(void);
extern void im_int_stub_206(void);
extern void im_int_stub_207(void);
extern void im_int_stub_208(void);
extern void im_int_stub_209(void);
extern void im_int_stub_210(void);
extern void im_int_stub_211(void);
extern void im_int_stub_212(void);
extern void im_int_stub_213(void);
extern void im_int_stub_214(void);
extern void im_int_stub_215(void);
extern void im_int_stub_216(void);
extern void im_int_stub_217(void);
extern void im_int_stub_218(void);
extern void im_int_stub_219(void);
extern void im_int_stub_220(void);
extern void im_int_stub_221(void);
extern void im_int_stub_222(void);
extern void im_int_stub_223(void);
extern void im_int_stub_224(void);
extern void im_int_stub_225(void);
extern void im_int_stub_226(void);
extern void im_int_stub_227(void);
extern void im_int_stub_228(void);
extern void im_int_stub_229(void);
extern void im_int_stub_230(void);
extern void im_int_stub_231(void);
extern void im_int_stub_232(void);
extern void im_int_stub_233(void);
extern void im_int_stub_234(void);
extern void im_int_stub_235(void);
extern void im_int_stub_236(void);
extern void im_int_stub_237(void);
extern void im_int_stub_238(void);
extern void im_int_stub_239(void);
extern void im_int_stub_240(void);
extern void im_int_stub_241(void);
extern void im_int_stub_242(void);
extern void im_int_stub_243(void);
extern void im_int_stub_244(void);
extern void im_int_stub_245(void);
extern void im_int_stub_246(void);
extern void im_int_stub_247(void);
extern void im_int_stub_248(void);
extern void im_int_stub_249(void);
extern void im_int_stub_250(void);
extern void im_int_stub_251(void);
extern void im_int_stub_252(void);
extern void im_int_stub_253(void);
extern void im_int_stub_254(void);
extern void im_int_stub_255(void);
*/

static void idt_set_gate(uint8_t num, uint32_t base, uint16_t selector,
			 uint8_t flags)
{
	idt[num].base_low = base & 0xFFFF;
	idt[num].base_high = (base >> 16) & 0xFFFF;
	idt[num].kernel_segment_selector = selector;
	idt[num].zero = 0;
	idt[num].flags = flags;
}

void idt_init()
{
	idt_ptr.limit = (sizeof(idt) * ARTILLERYOS_MAX_INTERRUPT_SIZE) - 1;
	idt_ptr.base = (uint32_t)&idt;

	memset(&idt, 0, (sizeof(idt) * ARTILLERYOS_MAX_INTERRUPT_SIZE) - 1);

	//idt_set_gate(0, (uint32_t)im_int_stub_0, 0x08, 0x8E);
	//idt_set_gate(1, (uint32_t)isr1, 0x08, 0x8E);

	// load idt
	__asm__ __volatile__("lidt %0" : : "m"(idt_ptr));

	// enable interrupts
	__asm__ __volatile__("sti;");
}

// General exception handler
void exception_handler()
{
	printf("INTERRUPT!\n");
	__asm__ volatile("cli; hlt"); // Completely hang CPU
}